env:
  TF_VAR_code_version: "1_0_1"

steps:
  - command: "bucket.sh"
    label: "Bucket check"
    env:
      TFE_ORG: "snapshot_tf_serverless"
      TFE_TOKEN: "fU6YgcpG6yHxqA.atlasv1."
      TFE_WORKSPACE: "s3-bucket-workspace"

  - command: "upload.sh"
    label: "Upload"
    env:
      AWS_ACCESS_KEY_ID: ""
      AWS_SESSION_TOKEN: "
      AWS_SECRET_ACCESS_KEY: ""
     # AWS_SESSION_EXPIRATION: 1599069759

  - command: "tf_workspace.sh"
    label: "Plan"
    env:
      TFE_ORG: "snapshot_tf_serverless"
      TFE_TOKEN: "fU6YgcpG6yHxqA.atlasv1."
      TFE_WORKSPACE: "lambda-workspace"

  - block: "Check Plan and Approve"

  - command: "tf_run.sh"
    label: "Run"
    env:
      TFE_ORG: "snapshot_tf_serverless"
      TFE_TOKEN: "fU6YgcpG6yHxqA.atlasv1."
      TFE_WORKSPACE: "lambda-workspace"