env:
  TF_VAR_code_version: "1_0_1"

steps:
  - command: "bucket.sh"
    label: "Bucket check"
    env:
      TFE_ORG: "snapshot_tf_serverless"
      TFE_TOKEN: "fU6YgcpG6yHxqA.atlasv1.sFPeVdPWNeMOozahdpCL4kEnuWOfy25FjIYlz68S18i5yf9p4gZqwz3ltvyR6skwNUA"
      TFE_WORKSPACE: "s3-bucket-workspace"

  - command: "upload.sh"
    label: "Upload"
    env:
      AWS_ACCESS_KEY_ID: "ASIA2LEU5EPEH54KPL5U"
      AWS_SESSION_TOKEN: "IQoJb3JpZ2luX2VjEJL//////////wEaCXVzLWVhc3QtMSJHMEUCIQDffyU071ToHoTs1Z3JDvCr3+O9nBn1FP7wZYHN7JnijQIgIr28hPGfjlbEmtUMAJCAReqAgylY6S7kTBvclUtumlMq9QMIi///////////ARAAGgw3MTExMjkzNzU2ODgiDFpII6AWRIrhaMGNkyrJA6gJeQFN9V4RA2KSQlxrsVYKwXs4sDB6DjyEa8JC9xlLhKGf/Ab1kycl1njoNSkztCSQLka3R91PoxeIGE7ZTviHscVDcOSe7Kk5FCU4sxsxuhSubzLGWE5HfcJxPA7e3hhfz54NV/1ATF010txXwWjpz7NvLqhNjBaNwwCYVonS6c4DMClcew7VdLjJ66VxvU216JCNIDtjPnBgLyXp3qvdL1qYU7d+2pixVvHeEiRSLJeHaK3pMuvn39bITMhFKX+p5NT+t5Ivwg5gNEUrwFArpTzt/Hj17OgsYJgWcRYowrTebVItzYxkfvmuMhs3T1S8x+05uPvE7QjvVkGFqYbxXPtiUfckPlc1X/M+BC+px2FyXeJZrKE77PDLLDw4DHK9o4/Nxgn0WIgfNcTRd7+qnGBomx/bsiSz7svg+y+aJxrfY7BgPA7kfTvuXK18kQkrdbucxGh2Q18TML+3zEjovRAQPoUtfDssJ6yhhgfYM9xtTSKIk4ppv3qMxKVD827PwS37TVtKVjkCnJtQEcy1mgs/dayls21W5tO/qw0+HX30AUTi87V++72b9S0sxC9AMHyc4rjhHVT5eP98ay5iIzg49NWwb7swv9u9+gU6nQF7u8trKxn2Zl7e9ViP4GcyfV+cplmRLnw0Gu1v0F/j2uceVSTFt2IyAEGLcvt1upJ30TYSTCP22agccmPOdjqFejjg6Nx/kea1kaO70b4Zdl6pfIkGSQ0g6jkDUbsJ0wlM7c14+zgq7jRAiInGhFGo4245elt86IcGAhChROd/uuk9RKF09BwAeToI/jvFXKXRSpN7N3HfftyWYaWA && export AWS_SESSION_EXPIRATION=1599069759JSP-MBP:lambda-test jsp$ export AWS_ACCESS_KEY_ID=ASIA2LEU5EPEH54KPL5U && export AWS_SECRET_ACCESS_KEY=mmUCIQDffyU071ToHoTs1Z3JDvCr3+O9nBn1FP7wZYHN7JnijQIgIr28hPGfjlbEmtUMAJCAReqAgylY6S7kTBvclUtumlMq9QMIi///////////ARAAGgw3MTExMjkzNzU2ODgiDFpII6AWRIrhaMGNkyrJA6gJeQFN9V4RA2KSQlxrsVYKwXs4sDB6DjyEa8JC9xlLhKGf/Ab1kycl1njoNSkztCSQLka3R91PoxeIGE7ZTviHscVDcOSe7Kk5FCU4sxsxuhSubzLGWE5HfcJxPA7e3hhfz54NV/1ATF010txXwWjpz7NvLqhNjBaNwwCYVonS6c4DMClcew7VdLjJ66VxvU216JCNIDtjPnBgLyXp3qvdL1qYU7d+2pixVvHeEiRSLJeHaK3pMuvn39bITMhFKX+p5NT+t5Ivwg5gNEUrwFArpTzt/Hj17OgsYJgWcRYowrTebVItzYxkfvmuMhs3T1S8x+05uPvE7QjvVkGFqYbxXPtiUfckPlc1X/M+BC+px2FyXeJZrKE77PDLLDw4DHK9o4/Nxgn0WIgfNcTRd7+qnGBomx/bsiSz7svg+y+aJxrfY7BgPA7kfTvuXK18kQkrdbucxGh2Q18TML+3zEjovRAQPoUtfDssJ6yhhgfYM9xtTSKIk4ppv3qMxKVD827PwS37TVtKVjkCnJtQEcy1mgs/dayls21W5tO/qw0+HX30AUTi87V++72b9S0sxC9AMHyc4rjhHVT5eP98ay5iIzg49NWwb7swv9u9+gU6nQF7u8trKxn2Zl7e9ViP4GcyfV+cplmRLnw0Gu1v0F/j2uceVSTFt2IyAEGLcvt1upJ30TYSTCP22agccmPOdjqFejjg6Nx/kea1kaO70b4Zdl6pfIkGSQ0g6jkDUbsJ0wlM7c14+zgq7jRAiInGhFGo4245elt86IcGAhChROd/uuk9RKF09BwAeToI/jvFXKXRSpN7N3HfftyWYaWA"
      AWS_SECRET_ACCESS_KEY: "mmWYT9jWGy9vyiOgZOfTCKGXOz2UoZ5U3mwIH8Us"
      AWS_SESSION_EXPIRATION: 1599069759

  - command: "tf_workspace.sh"
    label: "Plan"
    env:
      TFE_ORG: "snapshot_tf_serverless"
      TFE_TOKEN: "fU6YgcpG6yHxqA.atlasv1.sFPeVdPWNeMOozahdpCL4kEnuWOfy25FjIYlz68S18i5yf9p4gZqwz3ltvyR6skwNUA"
      TFE_WORKSPACE: "lambda-workspace"

  - block: "Check Plan and Approve"

  - command: "tf_run.sh"
    label: "Run"
    env:
      TFE_ORG: "snapshot_tf_serverless"
      TFE_TOKEN: "fU6YgcpG6yHxqA.atlasv1.sFPeVdPWNeMOozahdpCL4kEnuWOfy25FjIYlz68S18i5yf9p4gZqwz3ltvyR6skwNUA"
      TFE_WORKSPACE: "lambda-workspace"